# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Thesis/DAS_v2/DAS/DAS.srcs/sources_1/bd/Jupyter/ip/Jupyter_processing_system7_0_1/Jupyter_processing_system7_0_1.xci
# IP: The module: 'Jupyter_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Thesis/DAS_v2/DAS/DAS.gen/sources_1/bd/Jupyter/ip/Jupyter_processing_system7_0_1/Jupyter_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Jupyter_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Thesis/DAS_v2/DAS/DAS.srcs/sources_1/bd/Jupyter/ip/Jupyter_processing_system7_0_1/Jupyter_processing_system7_0_1.xci
# IP: The module: 'Jupyter_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Thesis/DAS_v2/DAS/DAS.gen/sources_1/bd/Jupyter/ip/Jupyter_processing_system7_0_1/Jupyter_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Jupyter_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
