# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constraints.xdc

# Block Designs: bd/Jupyter/Jupyter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter || ORIG_REF_NAME==Jupyter} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_processing_system7_0_1/Jupyter_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_processing_system7_0_1 || ORIG_REF_NAME==Jupyter_processing_system7_0_1} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_rst_ps7_0_100M_3/Jupyter_rst_ps7_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_rst_ps7_0_100M_3 || ORIG_REF_NAME==Jupyter_rst_ps7_0_100M_3} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_axi_dma_0_1/Jupyter_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_axi_dma_0_1 || ORIG_REF_NAME==Jupyter_axi_dma_0_1} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_xbar_0/Jupyter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_xbar_0 || ORIG_REF_NAME==Jupyter_xbar_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_ps7_0_axi_periph_2/Jupyter_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_ps7_0_axi_periph_2 || ORIG_REF_NAME==Jupyter_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_axi_gpio_0_0/Jupyter_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_axi_gpio_0_0 || ORIG_REF_NAME==Jupyter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_main_0_0/Jupyter_main_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_main_0_0 || ORIG_REF_NAME==Jupyter_main_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_AD7091R_0_0/Jupyter_AD7091R_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_AD7091R_0_0 || ORIG_REF_NAME==Jupyter_AD7091R_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_fifo_generator_0_0/Jupyter_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_fifo_generator_0_0 || ORIG_REF_NAME==Jupyter_fifo_generator_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_dac_top_0_0/Jupyter_dac_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_dac_top_0_0 || ORIG_REF_NAME==Jupyter_dac_top_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_edge_detector_0_0/Jupyter_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_edge_detector_0_0 || ORIG_REF_NAME==Jupyter_edge_detector_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_AD7091R_1_0/Jupyter_AD7091R_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_AD7091R_1_0 || ORIG_REF_NAME==Jupyter_AD7091R_1_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_main_1_0/Jupyter_main_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_main_1_0 || ORIG_REF_NAME==Jupyter_main_1_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_fifo_generator_1_0/Jupyter_fifo_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_fifo_generator_1_0 || ORIG_REF_NAME==Jupyter_fifo_generator_1_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_dma_multiplexer_0_1/Jupyter_dma_multiplexer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_dma_multiplexer_0_1 || ORIG_REF_NAME==Jupyter_dma_multiplexer_0_1} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_AD7091R_2_0/Jupyter_AD7091R_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_AD7091R_2_0 || ORIG_REF_NAME==Jupyter_AD7091R_2_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_AD7091R_3_0/Jupyter_AD7091R_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_AD7091R_3_0 || ORIG_REF_NAME==Jupyter_AD7091R_3_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_main_2_0/Jupyter_main_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_main_2_0 || ORIG_REF_NAME==Jupyter_main_2_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_main_3_0/Jupyter_main_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_main_3_0 || ORIG_REF_NAME==Jupyter_main_3_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_fifo_generator_1_1/Jupyter_fifo_generator_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_fifo_generator_1_1 || ORIG_REF_NAME==Jupyter_fifo_generator_1_1} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_fifo_generator_1_2/Jupyter_fifo_generator_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_fifo_generator_1_2 || ORIG_REF_NAME==Jupyter_fifo_generator_1_2} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_axi_interconnect_0_0/Jupyter_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_axi_interconnect_0_0 || ORIG_REF_NAME==Jupyter_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_auto_pc_0/Jupyter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_auto_pc_0 || ORIG_REF_NAME==Jupyter_auto_pc_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_auto_pc_1/Jupyter_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_auto_pc_1 || ORIG_REF_NAME==Jupyter_auto_pc_1} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_auto_ds_0/Jupyter_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_auto_ds_0 || ORIG_REF_NAME==Jupyter_auto_ds_0} -quiet] -quiet

# IP: bd/Jupyter/ip/Jupyter_auto_pc_2/Jupyter_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Jupyter_auto_pc_2 || ORIG_REF_NAME==Jupyter_auto_pc_2} -quiet] -quiet

# XDC: d:/Thesis/DAS_v2/DAS/DAS.gen/sources_1/bd/Jupyter/Jupyter_ooc.xdc
